pipeline:
  name: healet-webapp
  identifier: healetwebapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: Healet-webapp
        build: <+input>
  stages:
    - stage:
        name: sonar
        identifier: sonar
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Sonarqube
                      name: Sonarqube
                      identifier: Sonarqube
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          workspace: /harness-t_er7mnMSgiIKj-up_TRdQ
                          detection: auto
                        advanced:
                          log:
                            level: info
                        auth:
                          access_token: sqp_585e41ba240422e3aef6e8ce9ff44ef5212a91ba
                          domain: http://13.50.246.10:9000
                          ssl: true
                  - step:
                      type: Run
                      name: Run_1
                      identifier: Run_1
                      spec:
                        shell: Sh
                        command: pwd
