service:
  name: prod-svc
  identifier: prodsvc
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: proddeployment
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: github
                  gitFetchType: Branch
                  paths:
                    - prod.yaml
                  repoName: Healet-webapp
                  branch: harness
              skipResourceVersioning: false
              enableDeclarativeRollback: false
    type: Kubernetes
