infrastructureDefinition:
  name: prod
  identifier: prod
  orgIdentifier: default
  projectIdentifier: default_project
  environmentRef: staging
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: k8connector
    namespace: prod
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: false
