pipeline:
  name: webapp
  identifier: webapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: "Build and push to dockerhub "
                  identifier: Build_and_push_to_dockerhub
                  spec:
                    connectorRef: dockerhub
                    repo: pritidevops/harness-webapp
                    tags:
                      - "1"
                    caching: true
              - step:
                  type: Sonarqube
                  name: Sonarqube
                  identifier: Sonarqube
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: b09b6d0ffc193609b2cd5fd0009489d04bc329ba
                      domain: http://192.168.6.99:9000
                      ssl: false
                    tool:
                      project_key: harness
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: Healet-webapp
        build: <+input>
