apiVersion: apps/v1
kind: Deployment
metadata:
  name: healet-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: harness-healet
          image: pritidevops/harness-healet
          ports:
            - containerPort: 9090


---

apiVersion: v1
kind: Service
metadata:
  name: healet-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30001
