apiVersion: apps/v1
kind: Deployment
metadata:
  name: healet-deploy
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: healetapp
          image: pritidevops/harness-healet
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: healet-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
