name: web-application deployment

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3.6.1

            - name: Login DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Building Docker Image
              run: docker build -t healet:latest . 

            - name: Tagging Docker Images
              uses: docker tag healet:latest $((DOCKER_USERNAME))/healet:latest

            - name: Pushing Docker images to DockerHub
              uses: docker push $((DOCKER_USERNAME))/healet:latest

            
